
spring:
  http:
    multipart:
      max-file-size: 10MB
  cloud:
    stream:
      bindings:
        input:
          group: learning-spring-boot
        output:
          group: learning-spring-boot
logging:
  level:
    org:
      rabbitmq: TRACE
      springframework:
        amqp: TRACE
        cloud: TRACE
        integration: TRACE
